services:
  - type: web
    name: vovabulary-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vovabulary-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: vovabulary-db
    plan: free